apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-frontend
  labels:
    app: nextjs-frontend
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs-frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: nextjs-frontend
        tier: frontend
    spec:
      containers:
      - name: nextjs-app
        image: your-nextjs-app:latest  # Replace with your actual image
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always