apiVersion: v1
kind: Service
metadata:
  name: nextjs-frontend-service
  labels:
    app: nextjs-frontend
    tier: frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: nextjs-frontend
    tier: frontend