apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
  labels:
    app: laravel
    component: config

data:
  APP_NAME: "LaravelApp"
  APP_ENV: "production"
  APP_DEBUG: "false"
  LOG_CHANNEL: "stack"
  LOG_LEVEL: "info"
  QUEUE_CONNECTION: "redis"
  CACHE_DRIVER: "redis"
  SESSION_DRIVER: "redis"
  SESSION_LIFETIME: "120"
  BROADCAST_DRIVER: "redis"
  FILESYSTEM_DISK: "public"
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_DATABASE: "laravel"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_CACHE_DB: "1"