apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-nginx-config
  labels:
    app: laravel
    component: web

data:
  default.conf: |
    server {
      listen 8080;
      server_name _;
      root /var/www/html/public;
      index index.php index.html;

      location /healthz { return 200 'ok'; }

      location / {
        try_files $uri $uri/ /index.php?$query_string;
      }

      location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
      }

      location ~* \.(?:jpg|jpeg|png|gif|css|js|ico|svg)$ {
        expires 7d;
        access_log off;
      }
    }